# Generated by Django 5.2.7 on 2025-11-03 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14)])),
                ('endereco', models.CharField(max_length=255)),
                ('data_fundacao', models.DateField()),
            ],
        ),
    ]
