# Generated by Django 5.2.7 on 2025-11-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='percentual_vendido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
